AY2122S1-CS2103T-T10-1/tp

src/main/java/seedu/address/logic/Logic.java

Minor Refactor

---

docs/DeveloperGuide.md

Developer Guide Use Case Ordering

---

README.md

Changes:
* Update user guide link to User Guide in our product page instead of Notion document
* Add link to Developer Guide
* Some minor reformatting

Update links in Readme.md

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java

Add command `find t/TAG [MORE_TAGS]`
E.g. If user the user wants to search for contacts tagged as friends or family, they would enter `find t/friends family`
List of contacts tagged as friends or family will be displayed.

Add find by tags feature

---

src/main/java/seedu/address/logic/commands/ExportCommand.java

Fix format for ExportCommand invalid format

---

docs/UserGuide.md

Added find by telegram handle(s) as the third format for the find function and included it in the command summary table as well.

Update UserGuide.md to include find by telegram handle(s) feature

---

src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/ui/PersonDetails.java
src/main/resources/view/PersonDetails.fxml

Users can now click on the telegram handle displayed in the contact details and be directed to the t.me link on their browser.

Add clickable telegram handle

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/CommandHistory.java
src/main/java/seedu/address/ui/UserStringHistory.java

Just like a command line interface, when in the Command Box:
* Up arrow key will retrieve the previous command entered. After oldest command, up arrow will continue to show oldest command.
* Down arrow key will retrieve the next command entered. After the most recent command, down arrow will show empty Text Field.
Fixes #75 and #79

Implement up and down arrows keys to access previous commands

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/util/UserProfileWatcher.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ProfileSetUpWindow.java
src/main/java/seedu/address/ui/UserProfileInMenuBar.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/UserProfileInMenuBar.fxml

> `Fixed the Bug`
Bug Description:
When the User Name was being updated
via the edit command, the name on the
menu bar did not change, however
internally the name was changed. On
restarting the application, the changed/new
name could be observed.
Bug Fixed:
Now, as the User updates their name,
the changes on the menu bar are also
reflected immediately.

Fix GUI Bug: Name Not Update in Menu Bar

---

docs/DeveloperGuide.md

Minor updates to the regex used for `Github` and `Telegram`.

Update regex in Developer Guide

---

docs/UserGuide.md

Edit profile is now a separate feature from the edit feature.
Separation is done to prevent confusion.

Separate `edit profile` feature from `edit` feature in User Guide.

---

src/main/resources/view/ProfileSetUpWindow.fxml

Updated the title to: Profile Set Up

Update ProfileSetUpWindow Title

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/model/person/NameTest.java

Added more specific error messages for the find feature.

Find feature bug fix

---

src/main/java/seedu/address/model/person/IsEventTagPredicate.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TabPaneHeader.java

Resolves #191, event tab shows contacts with event tags.

Fix Event Tab

---

src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml
src/main/resources/view/TableView.css

* Updated the Help Section in the App.
> TO REVIEWER, 
>
> PLEASE VERIFY ALL COMMANDS AND THEIR FORMATS AS WELL.
>
> IF ANY DISCREPANCIES ARE FOUND, LET ME KNOW ASAP!
>
> THANX! 😄

Update Help Section in App

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/FavouriteCommand.java
src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java

Users will no longer be able to favourite a favourited person.
Users will no longer be able to unfavourite an unfavourited person.

Update Favourite and Unfavourite Command

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

The error message now specifies the compulsory fields that are missing.

Update Add Command error messages

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/ImportCommand.java
src/main/java/seedu/address/logic/commands/ShowCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ShowCommandParser.java
src/main/java/seedu/address/model/person/Github.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Telegram.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/storage/CsvAdaptedPerson.java
src/main/java/seedu/address/storage/JsonAdaptedTag.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/ShowCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
src/test/java/seedu/address/model/person/PersonTest.java

More v1.4 Bug Fixes

---

src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/commands/TagCommand.java
src/test/java/seedu/address/AppParametersTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java

Added new tests and fixed minor bugs.

Increase Test Coverage

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Update find by tag to be case insensitive and any new tag added to be automatically stored in lowercase.
Closes #236.

Update find by tag to be case insensitive 

---

docs/UserGuide.md

Find section of UG updated to be more comprehensive with the inclusion of all possible search parameters and constraints (where applicable).
Closes #168

Update find section of UG

---

docs/UserGuide.md

Changes:
* Fixes #193 by contextualising the introduction
* Fixes #166 by reordering the keyboard command section

Fixes for v1.4 bugs

---

docs/UserGuide.md

Add Tag command details to features and command summary.

Add tag command

---

docs/UserGuide.md

Fixes #190 by clarifying the import command in user guide.

Clarify import command

---

src/test/java/seedu/address/commons/util/LangColorUtilTest.java
src/test/java/seedu/address/logic/ai/AiTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Add Test Cases for AI and LangColorUtil

---

docs/UserGuide.md

Previously fixed bug where favourited contacts can be favourited again and unfavourited contacts can be unfavourited again.

Update definition of favourite and unfavourite features in User Guide

---

src/test/java/seedu/address/model/person/FindABuddyPredicateTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/util/SampleDataUtilTest.java

Add More Test Cases

---

src/main/java/seedu/address/logic/commands/FavouriteCommand.java
src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
src/test/java/seedu/address/model/person/FindABuddyPredicateTest.java

More Test Cases

---

src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/TagCommandParser.java
src/main/java/seedu/address/logic/parser/exceptions/ParseException.java

Added bug fixes for :
1. Non specific error messages for tag command
2. Absence of error message when trying to delete non existent tag
3. Absence of error message when trying to add existing tag
Closes #246, #247, #251.

Tag command bug fix

---

src/main/java/seedu/address/logic/commands/TagCommand.java

Clearer output for adding tags and removing tags.

Add specific output for `TagCommand`.

---

docs/UserGuide.md

Added Tag command section to UG. 
Closes #267.

Update Tag command section of UG

---

src/main/java/seedu/address/model/tag/Tag.java
src/test/java/seedu/address/commons/util/GitHubUtilTest.java
src/test/java/seedu/address/commons/util/StringUtilTest.java
src/test/java/seedu/address/model/person/AddressTest.java
src/test/java/seedu/address/model/person/EmailTest.java
src/test/java/seedu/address/model/person/GithubTest.java
src/test/java/seedu/address/model/person/IsEventTagPredicateTest.java
src/test/java/seedu/address/model/person/IsFavouritePredicateTest.java
src/test/java/seedu/address/model/person/NameTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/TelegramTest.java

Add Test Cases

---

docs/UserGuide.md
src/main/java/seedu/address/model/person/Telegram.java

Minor bug fixes

---

docs/UserGuide.md

Minor edits made to edit profile and tag command sections of UG.

Add minor edits to UG

---

docs/DeveloperGuide.md

The following use cases have been added : 
Use case 4 : Edit profile
Use case 5 : Add Tags
Use case 6 : Remove Tags
Use case 9 : Find by Github
Use case 10 : Find by Telegram

Update dg use cases

---

docs/DeveloperGuide.md

Fix ordered list in Tab switching

Fix formatting issue in DG

---

docs/DeveloperGuide.md

Fix ordered list

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/commands/ImportCommand.java
src/main/java/seedu/address/storage/CsvAdaptedPerson.java

Refactored:
* CommandResult
* CsvAdaptedPerson
* ImportCommand
* ExportCommand
Fixed:
* Add more specific message for Import and Export

Minor Refactor and Bug Fix
